export const airports = { 
    'Birmingham, Alabama': [BHM], 
    'Dothan, Alabama': [DHN], 
    'Huntsman, Alabama': [HSV], 
    'Mobile, Alabama': [MOB], 
    'Montgomery, Alabama': [MGM], 
    'Anchorage, Alaska': [LHD, MRI, ANC], 
    'Aniak, Alaska': [ANI], 
    'Barrow, Alaska': [BRW], 
    'Bethel, Alaska': [BET], 
    'Cordova, Alaska': [CDV], 
    'Deadhorse, Alaska': [SCC], 
    'Dilingham, Alaska': [DLG], 
    'Fairbanks, Alaska': [FAI], 
    'Galena, Alaska': [GAL], 
    'Gustavus, Alaska': [GST], 
    'Homer, Alaska': [HOM], 
    'Hoonah, Alaska': [HNH], 
    'Juneau, Alaska': [JNU], 
    'Kenai, Alaska': [ENA], 
    'Ketchikan, Alaska': [KTN], 
    'King Salmon, Alaska': [AKN], 
    'Kodiak, Alaska': [ADQ], 
    'Kotzebue, Alaska': [OTZ], 
    'Nome, Alaska': [OME], 
    'Petersburg, Alaska': [PSG], 
    'Sitka, Alaska': [SIT], 
    'St. Marys, Alaska': [KSM], 
    'Unalakleet, Alaska': [UNK],
    'Unalaska, Alaska': [DUT],  
    'Valdez, Alaska': [VDZ], 
    'Wrangell, Alaska': [WRG], 
    'Yakutat, Alaska': [YAK], 
    'Bullhead City , Arizona': [IFP], 
    'Flagstaff, Arizona': [FLG], 
    'Grand Canyon, Arizona': [GCN], 
    'Mesa, Arizona': [IWA], 
    'Page, Arizona': [PGA], 
    'Peach Springs, Arizona': [GCW], 
    'Phoenix, Arizona': [PHX], 
    'Tucson, Arizona': [TUS], 
    'Yuma, Arizona': [YUM], 
    'Fayetteville, Arkansas':[XNA], 
    'Fort Smith, Arkansas':[FSM], 
    'Little Rock, Arkansas':[LIT], 
    'Texarkana, Arkansas':[TXK], 
    'Arcata, California':[ACV], 
    'Bakersfield, California':[BFL], 
    'Burbank, California':[BUR], 
    'Carlsbad, California':[CLD], 
    'Chico, California':[CIC], 
    'Crescent City, California':[CEC], 
    'Fresno, California':[FAT], 
    'Long Beach, California':[LGB], 
    'Los Angeles, California':[LAX], 
    'Mammoth Lakes, California':[MMH], 
    'Modesto, California':[MOD], 
    'Monterey, California':[MRY], 
    'Oakland, California':[OAK], 
    'Ontario, California':[ONT], 
    'Palm Springs, California':[PSP], 
    'Redding, California':[RDD], 
    'Sacramento, California':[SMF], 
    'San Diego, California':[SAN], 
    'San Francisco, California':[SFO], 
    'San Jose, California':[SJC], 
    'San Luis Obispo, California':[SBP], 
    'Santa Ana, California':[SNA], 
    'Santa Barbara, California':[SBA], 
    'Santa Maria, California':[SMX], 
    'Santa Rosa, California':[STS], 
    'Stockton, California':[SCK], 
    'Aspen, Colorado':[ASE], 
    'Colorado Springs, Colorado':[COS], 
    'Denver, Colorado':[DEN], 
    'Durango, Colorado':[DRO], 
    'Eagle, Colorado':[EGE], 
    'Grand Junction, Colorado':[GJT], 
    'Gunnison, Colorado':[GUT], 
    'Hayden, Colorado':[HDN], 
    'Montrose, Colorado':[MJT], 
    'Hartford, Connecticut':[BDL], 
    'New Haven, Connecticut':[HVN],
    'Wilmington, Delaware':[ILG], 
    'Daytona Beach, Florida':[DAB], 
    'Fort Lauderdale, Florida':[FLL], 
    'Fort Myers, Florida':[RSW], 
    'Gainesville, Florida':[GNV], 
    'Jacksonville, Florida':[JAX], 
    'Key West, Florida':[EYW], 
    'Melbourne, Florida':[MLB], 
    'Miami, Florida':[MIA], 
    'Orlando, Florida':[MCO], 
    'Sanford, Florida':[SFB], 
    'Panama City Beach, Florida':[ECP], 
    'Pensacola, Florida':[PNS], 
    'Punta Gorda, Florida':[PGD], 
    'Sarasota, Florida':[SRQ], 
    'St. Augustine, Florida':[UST], 
    'St. Petersburg, Florida':[PIE], 
    'Tallahassee, Florida':[TLH], 
    'Tampa, Florida':[TPA], 
    'Valparaiso, Florida':[VPS], 
    'Vero Beach, Florida':[VRB], 
    'West Palm Beach, Florida':[PBI], 
    'Albany, Georgia':[ABY], 
    'Atlanta, Georgia':[ATL], 
    'Augusta, Georgia':[AGS], 
    'Brunswick, Georgia':[BQK], 
    'Columbus, Georgia':[CSG], 
    'Savannah, Georgia':[SAV], 
    'Valdosta, Georgia':[VLD],
    'Hilo, Hawaii': [ITO],         
    'Honolulu, Hawaii': [HNL],         
    'Kahului, Hawaii': [OGG],         
    'Kailua-Kona, Hawaii': [KOA],         
    'Kaunakakai, Hawaii': [MKK],         
    'Lanai City, Hawaii': [LNY],         
    'Lihue, Hawaii': [LIH],
    'Boise, Idaho': [BOI],         
    'Hailey, Idaho': [SUN],         
    'Idaho Falls, Idaho': [IDA],         
    'Lewiston, Idaho': [LWS],         
    'Pocatello, Idaho': [PIH],         
    'Twin Falls, Idaho': [TWF],
    'Belleville, Illinois': [BLV], 
    'Bloomington Illinois': [BMI],                
    'Champaign, Illinois': [CMI],         
    'Chicago, Illinois': [ORD, MDW],         
    'Marion, Illinois': [MWA],         
    'Moline, Illinois': [MLI],         
    'Peoria, Illinois': [PIA],         
    'Quincy, Illinois': [UIN],         
    'Rockford, Illinois': [RFD],         
    'Springfield, Illinois': [SPI],
    'Evansville, Indiana': [EVV],             
    'Fort Wayne, Indiana': [FWA],             
    'Indianapolis, Indiana': [IND],             
    'South Bend, Indiana': [SBN],
    'Cedar Rapids, Iowa': [CID],             
    'Des Moines, Iowa': [DSM],             
    'Dubuque, Iowa': [DBQ],             
    'Sioux City, Iowa': [SUX],             
    'Waterloo, Iowa': [ALO],    
    'Garden City, Kansas': [GCK],             
    'Manhattan, Kansas': [MHK],             
    'Wichita, Kansas': [ICT],
    'Cincinnati, Kentucky': [CVG],
    'Lexington, Kentucky': [LEX],             
    'Louisville, Kentucky': [SDF],             
    'Owensboro, Kentucky': [OWB],             
    'Paducah, Kentucky': [PAH],
    'Alexandria, Louisiana': [AEX],             
    'Baton Rouge, Louisiana': [BTR],             
    'Lafayette, Louisiana': [LFT],             
    'Lake Charles, Louisiana': [LCH],             
    'Monroe, Louisiana': [MLU],             
    'New Orleans, Louisiana': [MSY],             
    'Shreveport, Louisiana': [SHV],
    'Bangor, Maine': [BGR],             
    'Portland, Maine': [PWM],             
    'Presque Isle, Maine': [PQI],             
    'Rockland, Maine': [RKD],
    'Baltimore, Maryland': [BWI],             
    'Salisbury, Maryland': [SBY],             
    'Hagerstown, Maryland': [HGR], 
    'Boston, Massachusetts': [BOS],             
    'Hyannis, Massachusetts': [HYA],             
    'Nantucket, Massachusetts': [ACK],             
    'Provincetown, Massachusetts': [PVC],             
    'Vineyard Haven, Massachusetts': [MVY],             
    'Worcester, Massachusetts': [ORH],
    'Alpena, Michigan': [APN],             
    'Detroit, Michigan': [DTW],             
    'Escanaba, Michigan': [ESC],             
    'Flint, Michigan': [FNT],             
    'Grand Rapids, Michigan': [GRR],             
    'Hancock, Michigan': [CMX],             
    'Iron Mountain, Michigan': [IMT],             
    'Kalamazoo, Michigan': [AZO],             
    'Lansing, Michigan': [LAN],             
    'Marquette, Michigan': [SAW],             
    'Muskegon, Michigan': [MKG],             
    'Pellston, Michigan': [PLN],             
    'Saginaw, Michigan': [MBS],             
    'Sault Ste. Marie, Michigan': [CIU], 
    'Traverse City, Michigan': [TVC],             
    'Bemidji, Minnesota': [BJI],             
    'Brainerd, Minnesota': [BRD],             
    'Duluth, Minnesota': [DLH],             
    'Hibbing, Minnesota': [HIB],             
    'International Falls, Minnesota': [INL],             
    'Minneapolis, Minnesota': [MSP],             
    'Rochester, Minnesota': [RST],             
    'St. Cloud, Minnesota': [STC],
    'Columbus, Mississippi': [GTR],             
    'Gulfport, Mississippi': [GPT],             
    'Hattiesburg, Mississippi': [PIB],             
    'Jackson, Mississippi': [JAN],    
    'Columbia, Missouri': [COU], 
    'Joplin, Missouri': [JLN],             
    'Kansas City, Missouri': [MCI],             
    'Springfield, Missouri': [SGF],             
    'St. Louis, Missouri': [STL],        
    'Billings, Montana': [BIL], 
    'Bozeman, Montana': [BZN], 
    'Butte, Montana': [BTM], 
    'Great Falls, Montana': [GTF], 
    'Helena, Montana': [HLN], 
    'Kalispell, Montana': [GPI], 
    'Missoula, Montana': [MSO],
    'Grand Island, Nebraska': [GRI],
    'Lincoln, Nebraska': [LNK], 
    'Omaha, Nebraska': [OMA], 
    'Boulder City, Nevada': [BLD], 
    'Elko, Nevada': [EKO], 
    'Las Vegas, Nevada': [LAS], 
    'Reno, Nevada': [RNO],
    'Lebanon, New Hampshire': [LEB], 
    'Manchester, New Hampshire': [MHT], 
    'Portsmouth, New Hampshire': [PSM],
    'Atlantic City, New Jersey': [ACY], 
    'Trenton, New Jersey': [TTN], 
    'Newark, New Jersey': [EWR],
    'Albuquerque, New Mexico': [ABQ], 
    'Farmington, New Mexico': [FMN], 
    'Hobbs, New Mexico': [HOB], 
    'Roswell, New Mexico': [ROW], 
    'Santa Fe, New Mexico': [SAF], 
    'Albany, New York': [ALB], 
    'Binghamton, New York': [BGM], 
    'Buffalo, New York': [BUF], 
    'Elmira, New York': [ELM], 
    'Islip, New York': [ISP], 
    'Ithaca, New York': [ITH], 
    'New York, New York': [JFK, LGA], 
    'Newburgh, New York': [SWF], 
    'Niagara Falls, New York': [IAG], 
    'Plattsburgh, New York': [PBG], 
    'Rochester, New York': [ROC], 
    'Syracuse, New York': [SYR], 
    'Watertown, New York': [ART], 
    'White Plains, New York': [HPN], 
    'Asheville, North Carolina': [AVL],
    'Charlotte, North Carolina': [CLT], 
    'Fayetteville, North Carolina': [FAY], 
    'Greensboro, North Carolina': [GSO], 
    'Greenville, North Carolina': [PGV], 
    'Jacksonville, North Carolina': [OAJ], 
    'New Bern, North Carolina': [EWN], 
    'Raleigh, North Carolina': [RDU], 
    'Wilmington, North Carolina': [ILM],
    'Bismarck, North Dakota': [BIS], 
    'Dickinson, North Dakota': [DIK], 
    'Fargo, North Dakota': [FAR], 
    'Grand Forks, North Dakota': [GFK], 
    'Minot, North Dakota': [MOT], 
    'Williston, North Dakota': [ISN],
    'Akron, Ohio': [CAK], 
    'Cincinnati, Ohio': [LUK], 
    'Cleveland, Ohio': [CLE], 
    'Columbus, Ohio': [CMH, LCK], 
    'Dayton, Ohio': [DAY], 
    'Toledo, Ohio': [TOL], 
    'Youngstown, Ohio': [YNG], 
    'Lawton, Oklahoma': [LAW], 
    'Oklahoma City, Oklahoma': [OKC], 
    'Tulsa, Oklahoma': [TUL],
    'Eugene, Oregon': [EUG], 
    'Klamath Falls, Oregon': [LMT], 
    'Medford, Oregon': [MFR], 
    'North Bend, Oregon': [OTH], 
    'Portland, Oregon': [PDX], 
    'Redmond, Oregon': [RDM], 
    'Allentown, Pennsylvania': [ABE], 
    'Erie, Pennsylvania': [ERI], 
    'Harrisburg, Pennsylvania': [MDT], 
    'Latrobe, Pennsylvania': [LBE], 
    'Philadelphia, Pennsylvania': [PHL], 
    'Pittsburg, Pennsylvania': [PIT], 
    'State College, Pennsylvania': [SCE], 
    'Wilkes-Barre, Pennsylvania': [AVP], 
    'Williamsport, Pennsylvania': [IPT],
    'Block Island, Rhode Island': [BID], 
    'Providence, Rhode Island': [PVD], 
    'Westerly, Rhode Island': [WST],
    'Charleston, South Carolina': [CHS], 
    'Columbia, South Carolina': [CAE], 
    'Florence, South Carolina': [FLO], 
    'Greenville, South Carolina': [GSP], 
    'Hilton Head Island, South Carolina': [HHH], 
    'Myrtle Beach, South Carolina': [MYR],
    'Aberdeen, South Dakota': [ABR], 
    'Pierre, South Dakota': [PIR], 
    'Rapid City, South Dakota': [RAP], 
    'Sioux Falls, South Dakota': [FSD],
    'Bristol, Tennessee': [TRI], 
    'Chattanooga, Tennessee': [CHA], 
    'Knoxville, Tennessee': [TYS], 
    'Memphis, Tennessee': [MEM], 
    'Nashville, Tennessee': [BNA],
    'Abilene, Texas': [ABI], 
    'Amarillo, Texas': [AMA], 
    'Austin, Texas': [AUS], 
    'Beaumont, Texas': [BPT], 
    'Brownsville, Texas': [BRO], 
    'College Station, Texas': [CLL], 
    'Corpus Christi, Texas': [CRP], 
    'Dallas, Texas': [DAL], 
    'Dallas-Fort Worth, Texas': [DFW], 
    'Del Rio, Texas': [DRT], 
    'El Paso, Texas': [ELP], 
    'Fort Hood, Texas': [GRK], 
    'Harlingen, Texas': [HWL], 
    'Houston, Texas': [IAH, HOU], 
    'Laredo, Texas': [LRD], 
    'Longview, Texas': [GGG], 
    'Lubbock, Texas': [LBB], 
    'McAllen, Texas': [LFE], 
    'Midland, Texas': [MAF], 
    'San Angelo, Texas': [SJT], 
    'San Antonio, Texas': [SAT], 
    'Tyler, Texas': [TYR], 
    'Waco, Texas': [ACT], 
    'Wichita Falls, Texas': [SPS], 
    'Provo, Utah': [PVU], 
    'Salt Lake City, Utah': [SLC], 
    'St. George, Utah': [SGU], 
    'Wendover, Utah': [ENV],
    'Burlington, Vermont': [BTV],
    'Charlottesville, Virginia': [CHO], 
    'Lynchburg, Virginia': [LYH], 
    'Newport News, Virginia': [PHF], 
    'Norfolk, Virginia': [ORF], 
    'Richmond, Virginia': [RIC], 
    'Roanoke, Virginia': [ROA], 
    'Staunton, Virginia': [SHD], 
    'Washington D.C., Virginia': [DCA, IAD],
    'Bellingham, Washington': [BLI], 
    'Friday Harbor, Washington': [FRD], 
    'Pasco, Washington': [PSC], 
    'Port Angeles, Washington': [CLM], 
    'Pullman, Washington': [PUW], 
    'Seattle, Washington': [BFI, SEA], 
    'Spokane, Washington': [GEG], 
    'Walla Walla, Washington': [ALW], 
    'Wenatchee, Washington': [EAT], 
    'Yakima, Washington': [YKM], 
    'Charleston, West Virginia': [CRW], 
    'Clarksburg, West Virginia': [CKB], 
    'Huntington, West Virginia': [HTS], 
    'Lewisburg, West Virginia': [LWB], 
    'Morgantown, West Virginia': [MGW],
    'Appleton, Wisconsin': [ATW], 
    'Eau Claire, Wisconsin': [EAU], 
    'Green Bay, Wisconsin': [GRB], 
    'La Crosse, Wisconsin': [LSE], 
    'Madison, Wisconsin': [MSN], 
    'Milwaukee, Wisconsin': [MKE], 
    'Mosinee, Wisconsin': [CWA], 
    'Rhinelander, Wisconsin': [RHI], 
    'Casper, Wyoming': [CPR], 
    'Cheyenne, Wyoming': [CYS], 
    'Cody, Wyoming': [COD], 
    'Gillete, Wyoming': [GCC], 
    'Jackson, Wyoming': [JAC], 
    'Riverton, Wyoming': [RIW], 
    'Rock Springs, Wyoming': [RKS],      
    'Sheridan, Wyoming': [SHR]
};